# algo param
algo_name: 'bc'

# network param
actor_hidden_size: [100, 100]

# env param
env_name: 'HalfCheetah-v2'

# others
use_d4rl: false  # whether to use d4rl dataset
d4rl_task_name: 'halfcheetah-expert-v2'
dataset: 'data/expert_data'  # use manually generated expert data if not use d4rl