# algo param
algo_name: bc
max_iters: 100_000
eval_freq: 500
batch_size: 128
expert_traj_num: 25
expert_buffer_size: 25_000
max_grad_norm: 10.
load_model: false
loss_fn: mse

# net param
actor_hidden_size: [100, 100]
actor_lr: !!float 3e-4

# env param
use_d4rl: true  # whether to use d4rl dataset
env_name:  halfcheetah-expert-v2  # walker2d-expert-v2, is more easy
# use_gen_data: true  # use manually generated expert data if not use d4rl
# dataset_path: ./data/expert_data/ant_expert-v2.hdf5

# others
seed: 0
device: cuda:0