# algo param
algo_name: 'bc'
num_epochs: 100

# network param
actor_hidden_size: [256, 256]
actor_lr: !!float 3e-4

# env param
env_name: 'HalfCheetah-v2'

# others
use_d4rl: true  # whether to use d4rl dataset
d4rl_task_name: 'halfcheetah-expert-v2'
dataset_name: 'halfcheetah_expert-v3'  # use manually generated expert data if not use d4rl