# algo param
algo_name: bc2
max_iters: 100_000
eval_freq: 500
expert_traj_num: 10
expert_buffer_size: 25_000
load_model: false

# env param
use_d4rl: true  # whether to use d4rl dataset
d4rl_task_name: walker2d-expert-v2 # halfcheetah-expert-v2

# others
seed: 0
device: cuda:0
bc:
  max_iters: 1_000
rl: