# algo param
algo_name: dagger
max_iters: 100_000
eval_freq: 500
batch_size: 128
expert_traj_num: 0
expert_buffer_size: 25_000
max_grad_norm: 10
load_model: false
norm_state: false
loss_fn: mse

query: true
expert_name: sac
expert_model: 'out/sac_HalfCheetah-v3_0/model.pt'
expert_config: sac.yml
rollout_freq: 5000
rollout_steps: 1000

# net param
actor_hidden_size: [100, 100]
actor_lr: !!float 3e-4

# env param
use_d4rl: false

# others
seed: 0
device: cuda:0