# algo param
algo_name: dagger
max_iters: 100_000
gamma: 0.
eval_freq: 500
batch_size: 128
expert_traj_num: 1  # \beta = 1
buffer_size: 30_000
max_grad_norm: 10
load_model: false
norm_state: false
loss_fn: mse
expert_model_path: ''

rollout_freq: 5000
rollout_step: 1000

# net param
actor_hidden_size: [100, 100]
actor_lr: !!float 3e-4

# env param
env_name: HalfCheetah-v2
use_d4rl: true  # whether to use d4rl dataset
d4rl_task_name: halfcheetah-expert-v2
dataset_name: halfcheetah_expert-v3  # use manually generated expert data if not use d4rl

# others
seed: 0
device: cuda:0