# algo param
algo_name: gail
batch_size: 128
eval_freq: 10
expert_traj_num: 20
expert_buffer_size: 20_000
max_iters: 1000

update_disc_times: 10

load_model: false
norm_state: false

# net param
discriminator_hidden_size: [100, 100]
discriminator_lr: !!float 3e-4

# env param
use_d4rl: true  # whether to use d4rl dataset
d4rl_task_name: halfcheetah-expert-v2

# others
seed: 0
device: "cuda:0"