# algo param
algo_name: ppo
rollout_steps: 2048
buffer_size: 2048
gamma: 0.99
max_timesteps: 1000_000
eval_freq: 5000
lambda: 0.95
epsilon_clip: 0.2
entropy_coef: 0.
value_coef: 0.5
batch_size: 64
max_grad_norm: 0.5
norm_state: true
update_times: 10

# net param
actor_hidden_size: [64, 64]
critic_hidden_size: [64, 64]
actor_lr: !!float 3e-4
critic_lr: !!float 3e-4

# others
seed: 0
device: cuda:0
