# algo param
algo_name: sac
rho: .005  # target network update rate
env_steps: 1  # update model after every env_steps
start_timesteps: 10000  # time steps initial random policy is used
fixed_alpha: false  # whether to fine-tune alpha
alpha: 1.0
alpha_lr: !!float 3e-4
