# algo param
algo_name: td3
rho: .005  # target network update rate
c: 0.5  # noise clip threshold for target policy
sigma: 0.2  # std of Gaussian for target actor
expl_std: 0.1  # std of Gaussian for exploration
start_timesteps: 25000  # time steps initial random policy is used
policy_delay: 2  # frequency of delayed policy updates
