# algo param
algo_name: trpo
rollout_steps: 2048
gamma: 0.995
buffer_size: 2048
lambda: 0.97
norm_state: true

# conjugate gradient param
residual_tol: !!float 1e-10
cg_steps: 10
damping: !!float 1e-1

# line search param
beta: 0.5
max_backtrack: 10
line_search_accept_ratio: 0.1
delta: !!float 1e-2

# network param
actor_hidden_size: [64, 64]
critic_hidden_size: [64, 64]
weight_decay: !!float 1e-3
n_critic_update: 5