# algo param
algo_name: trpo
rollout_steps: 2048
gamma: 0.995
buffer_size: 2048
lambda: 0.97
norm_state: true
gamma: 0.99  # discount factor
buffer_size: 1000_000
batch_size: 256
eval_freq: 5000
max_timesteps: 1000_000

# conjugate gradient param
residual_tol: !!float 1e-10
cg_steps: 10
damping: !!float 1e-1

# line search param
beta: 0.5
max_backtrack: 10
line_search_accept_ratio: 0.1
delta: !!float 1e-2

# net param
actor_hidden_size: [64, 64]
critic_hidden_size: [64, 64]
weight_decay: !!float 1e-3
critic_lr: !!float 3e-4
n_critic_update: 5

# env param
env_name: Walker2d-v3

# others
seed: 0
device: cuda:0